### ISSUE TITLE
Horizontal scrolling for tables

### ISSUE THREAD

**Issue by zabolotskii** [alexmojaki/oeis-explorer#1]
Thank you for this interesting and useful project.
I'd like to request an enhancement. Tables of common terms are quite often very wide. There is no way to view wide table in full without zooming out the whole page. Please make it possible. One possible solution is to add horizontal scrollbar to these tables.

**Comment by alexmojaki** [comment]
I'm glad you like it :)

I've added a horizontal scrollbar to the tables. It's not super easy to use if the table is also tall, but I think it's sufficient.
